---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-recommender-goa-deployment-ds2-v1.0.2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-recommender-goa
  template:
    metadata:
      labels:
        app: song-recommender-goa
    spec:
      containers:
      #Model container:
      - name: song-recommender-goa-model
        image: quay.io/gaolan/song-recomender-model:0.3
        imagePullPolicy: Always
        env:
        - name: MIN_CONFIDENCE
          value: "0.1"
        - name: MIN_SUPPORT_RATIO
          value: "0.1"
        - name: DATASET_ADDRESS
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"
        volumeMounts:
        - name: shared-volume
          mountPath: /app/data

        #Frontend container:
      - name: song-recommender-goa-frontend
        image: quay.io/gaolan/song-recomender-frontend:0.3
        ports:
        - containerPort: 50010
        env:
        - name: VERSION
          value: "1.0.2"
        - name: NB_RECOMENDATION_SONGS
          value: "3"
        volumeMounts:
        - name: shared-volume
          mountPath: /app/data
    
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: song-recommender-goa-pvc